### PR TITLE
Update AntiSpammer.php

### PR DESCRIPTION
**Pull request by xBeastMode**

### CODE REVIEW

**Comment by jasonw4331** [comment]
this plugin seems kinda useless with the current amount in circulation between servers

**Comment by xBeastMode** [comment]
What do you mean?

**Comment by jasonw4331** [comment]
there are already a lot of anti spamming plugins out

**Comment by xBeastMode** [comment]
Well, this plugin was made way before other spam plugins. ChatDefender was outdated so I decided to make a simpler version, I was attempting to create a simpler code but everytime a player chatted their message was blocked, I tried many methods until I made it work. I have been testing this plugin way back before many other AntiSpammer plugin, since like beginnings of 2015, and back at that time there weren't much Anti-spam plugins.

**Comment by jasonw4331** [comment]
that makes more sense

**Pull request closed without merging**
